export const routes = {
  landing: '/',
  login: '/login',
  signup: '/signup',
  dashboard: '/dashboard',
  competitions: '/competitions',
  teams: '/teams',
  teamCreate: '/teams/create',
  teamRequests: '/teams/requests',
  applications: '/applications',
  profile: '/profile',
  admin: '/admin',
  adminCompetitions: '/admin/competitions',
  adminSuggestions: '/admin/suggestions',
  adminModeration: '/admin/moderation',
}