export const routes = {
  landing: '/',
  login: '/login',
  signup: '/signup',
  dashboard: '/dashboard',
  competitions: '/competitions',
  teams: '/teams',
  applications: '/applications',
  profile: '/profile',
  profileEdit: '/profile/edit',
  admin: '/admin',
  adminCompetitions: '/admin/competitions',
  adminSuggestions: '/admin/suggestions',
  adminModeration: '/admin/moderation',
}
