export const seededCompetitions = [
  {
    _id: 'comp-1',
    title: 'KAUST Entrepreneurship Challenge',
    organizer: 'KAUST',
    category: 'Business',
    mode: 'Team',
    teamSize: '2-4',
    deadline: '2025-05-15',
    registrationDeadline: '2025-05-15',
    status: 'open',
    prize: 'SAR 50,000',
    description:
      'A national competition for university students to pitch innovative business ideas to a panel of investors and industry experts. Teams will go through multiple rounds of evaluation.',
    requirements: ['Business plan', 'Prototype or MVP', 'Pitch deck'],
    tags: ['Business', 'Entrepreneurship', 'Pitch'],
    links: [],
    startDate: '2025-05-20',
    endDate: '2025-05-24',
    participationType: 'team',
    createdBy: null,
  },
  {
    _id: 'comp-2',
    title: 'ACM ICPC Regional 2025',
    organizer: 'ACM',
    category: 'Competitive Programming',
    mode: 'Team',
    teamSize: '3',
    deadline: '2025-06-01',
    registrationDeadline: '2025-06-01',
    status: 'open',
    prize: 'Trophy + Advancement',
    description:
      'The ACM International Collegiate Programming Contest regional qualifier. Teams of exactly 3 will solve algorithmic problems under time pressure.',
    requirements: ['University enrollment', 'Team of 3', 'Prior ICPC participation optional'],
    tags: ['Programming', 'Algorithms', 'ICPC'],
    links: [],
    startDate: '2025-06-10',
    endDate: '2025-06-12',
    participationType: 'team',
    createdBy: null,
  },
  {
    _id: 'comp-3',
    title: 'Saudi Hackathon: Smart Cities',
    organizer: 'MCIT',
    category: 'Hackathon',
    mode: 'Team',
    teamSize: '3-5',
    deadline: '2025-04-28',
    registrationDeadline: '2025-04-28',
    status: 'open',
    prize: 'SAR 100,000',
    description:
      'Build innovative solutions for smart city challenges including transportation, sustainability, and civic infrastructure in a 48-hour hackathon.',
    requirements: ['Working prototype', 'Team of 3-5', 'University students only'],
    tags: ['Hackathon', 'Smart Cities', 'Tech'],
    links: [],
    startDate: '2025-05-01',
    endDate: '2025-05-03',
    participationType: 'team',
    createdBy: null,
  },
  {
    _id: 'comp-4',
    title: 'National Robotics Competition',
    organizer: 'KACST',
    category: 'Robotics',
    mode: 'Team',
    teamSize: '2-6',
    deadline: '2025-07-10',
    registrationDeadline: '2025-07-10',
    status: 'open',
    prize: 'SAR 30,000',
    description:
      'Design and build autonomous robots to complete a series of challenges. The competition tests mechanical engineering, programming, and teamwork.',
    requirements: ['Hardware prototype', 'Technical report', 'University team'],
    tags: ['Robotics', 'Engineering', 'Hardware'],
    links: [],
    startDate: '2025-07-16',
    endDate: '2025-07-20',
    participationType: 'team',
    createdBy: null,
  },
  {
    _id: 'comp-5',
    title: 'UX Design Sprint - FinTech',
    organizer: 'STC Pay',
    category: 'Design',
    mode: 'Team',
    teamSize: '2-3',
    deadline: '2025-05-05',
    registrationDeadline: '2025-05-05',
    status: 'open',
    prize: 'SAR 15,000',
    description:
      'A rapid design competition challenging teams to reimagine a fintech product experience in 72 hours. Judged on usability, aesthetics, and innovation.',
    requirements: ['Figma prototype', 'User research summary', 'Presentation'],
    tags: ['Design', 'UX', 'FinTech'],
    links: [],
    startDate: '2025-05-12',
    endDate: '2025-05-15',
    participationType: 'team',
    createdBy: null,
  },
  {
    _id: 'comp-6',
    title: 'AI for Healthcare Challenge',
    organizer: 'Saudi Health Council',
    category: 'AI / ML',
    mode: 'Team',
    teamSize: '2-4',
    deadline: '2025-03-30',
    registrationDeadline: '2025-03-30',
    status: 'closed',
    prize: 'SAR 75,000',
    description:
      'Develop AI-powered solutions to improve patient outcomes, diagnosis accuracy, or healthcare operations. Open to all university students.',
    requirements: ['Working model', 'Dataset documentation', 'Impact report'],
    tags: ['AI', 'Healthcare', 'Machine Learning'],
    links: [],
    startDate: '2025-04-05',
    endDate: '2025-04-08',
    participationType: 'team',
    createdBy: null,
  },
  {
    _id: 'COMP-8821',
    title: 'Neural Network Challenge 2026',
    organizer: 'KFUPM AI Club',
    category: 'AI / ML',
    mode: 'Hybrid',
    teamSize: '2-4',
    deadline: '2026-10-05',
    registrationDeadline: '2026-10-05',
    status: 'active',
    prize: 'SAR 24,000',
    description:
      'A university-wide applied AI competition focused on practical model building, evaluation quality, and research communication.',
    requirements: ['Student team', 'Demo submission'],
    tags: ['AI', 'University'],
    links: ['https://compitihub.local/neural-network-challenge'],
    startDate: '2026-10-12',
    endDate: '2026-11-30',
    participationType: 'team',
    createdBy: null,
  },
  {
    _id: 'COMP-9042',
    title: 'Cyber Security Regional Finals',
    organizer: 'Saudi Cyber Forum',
    category: 'Security',
    mode: 'Onsite',
    teamSize: '4',
    deadline: '2026-12-20',
    registrationDeadline: '2026-12-20',
    status: 'upcoming',
    prize: 'SAR 40,000',
    description:
      'Regional finals for student security teams competing across incident response, reverse engineering, and attack simulation tracks.',
    requirements: ['Qualified finalist roster'],
    tags: ['Security', 'CTF'],
    links: ['https://compitihub.local/cyber-finals'],
    startDate: '2027-01-01',
    endDate: '2027-01-15',
    participationType: 'team',
    createdBy: null,
  },
  {
    _id: 'COMP-7512',
    title: 'Global Data Mining Hackathon',
    organizer: 'DataLab MENA',
    category: 'Data Science',
    mode: 'Hybrid',
    teamSize: '3-5',
    deadline: '2026-07-22',
    registrationDeadline: '2026-07-22',
    status: 'ended',
    prize: 'SAR 18,000',
    description:
      'An intensive hackathon for student teams building data mining solutions for real-world academic and business datasets.',
    requirements: ['Dataset methodology note'],
    tags: ['Data', 'Hackathon'],
    links: ['https://compitihub.local/data-mining-hackathon'],
    startDate: '2026-08-01',
    endDate: '2026-08-15',
    participationType: 'team',
    createdBy: null,
  },
  {
    _id: 'COMP-9155',
    title: 'Robotics Systems Sprint',
    organizer: 'Engineering Deanship',
    category: 'Robotics',
    mode: 'Onsite',
    teamSize: '3-6',
    deadline: '2026-08-24',
    registrationDeadline: '2026-08-24',
    status: 'draft',
    prize: 'SAR 12,500',
    description:
      'Prototype-focused robotics sprint for multidisciplinary teams designing autonomous systems under constrained timelines.',
    requirements: ['Draft internal brief'],
    tags: ['Robotics', 'Prototype'],
    links: [],
    startDate: '2026-09-03',
    endDate: '2026-09-18',
    participationType: 'team',
    createdBy: null,
  },
]
