export const seedMemberDirectory = {
  'user-leader-1': { username: 'Ali Hassan', role: 'Team Leader' },
  'user-leader-2': { username: 'Reem Al-Zahrani', role: 'Team Leader' },
  'user-leader-3': { username: 'Mohammed Al-Ghamdi', role: 'Team Leader' },
  'user-leader-4': { username: 'Khalid Bin Nasser', role: 'Team Leader' },
  'user-leader-5': { username: 'Hessa Al-Dossari', role: 'Team Leader' },
  'user-2': { username: 'Sara Al-Otaibi', role: 'Member' },
  'user-3': { username: 'Faisal Omer', role: 'Backend' },
  'user-4': { username: 'Nora Khalid', role: 'Frontend' },
  'user-5': { username: 'Lama Saud', role: 'Business Analyst' },
  'user-6': { username: 'Dina Yousef', role: 'Mechanical Engineer' },
  'user-7': { username: 'Omar Taher', role: 'Electrical Engineer' },
  'user-8': { username: 'Tariq Saleh', role: 'UX Researcher' },
}

export const seededTeams = [
  {
    _id: 'team-1',
    name: 'ByteForge',
    competitionId: 'comp-2',
    leaderId: 'user-leader-1',
    description: 'A competitive programming team looking for a third member strong in graph theory and dynamic programming.',
    requiredSkills: ['Algorithms', 'Data Structures', 'C++'],
    totalSlots: 3,
    memberIds: ['user-leader-1', 'user-2'],
    status: 'recruiting',
  },
  {
    _id: 'team-2',
    name: 'NovaBuild',
    competitionId: 'comp-3',
    leaderId: 'user-leader-2',
    description: 'Full-stack smart cities team with the final UI/UX seat already filled and the sprint roadmap locked in.',
    requiredSkills: ['UI/UX Design', 'Figma', 'React'],
    totalSlots: 4,
    memberIds: ['user-leader-2', 'user-3', 'user-4', 'user-2'],
    status: 'full',
  },
  {
    _id: 'team-3',
    name: 'Venture X',
    competitionId: 'comp-1',
    leaderId: 'user-leader-3',
    description: 'We have a strong business concept in the EdTech space. Looking for a technical co-founder to build the MVP.',
    requiredSkills: ['Mobile Dev', 'React Native', 'Firebase'],
    totalSlots: 3,
    memberIds: ['user-leader-3', 'user-5'],
    status: 'recruiting',
  },
  {
    _id: 'team-4',
    name: 'SteelBot',
    competitionId: 'comp-4',
    leaderId: 'user-leader-4',
    description: 'Mechanical and electrical engineers building an autonomous navigation robot. Seeking a software engineer for computer vision.',
    requiredSkills: ['Python', 'Computer Vision', 'ROS'],
    totalSlots: 5,
    memberIds: ['user-leader-4', 'user-6', 'user-7', 'user-leader-1'],
    status: 'recruiting',
  },
  {
    _id: 'team-5',
    name: 'PixelFlow',
    competitionId: 'comp-5',
    leaderId: 'user-leader-5',
    description: 'Design-first team for the fintech UX sprint. Full team assembled.',
    requiredSkills: ['Figma', 'User Research', 'Prototyping'],
    totalSlots: 2,
    memberIds: ['user-leader-5', 'user-8'],
    status: 'full',
  },
]
